server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# h2
spring:
  datasource:
    url: jdbc:h2:mem:kpsecdb
    platform: h2
    username: kpsec
    password: kpsec
    driverClassName: org.h2.Driver
    generate-unique-name: false
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

  # jpa
  jpa:
    hibernate:
      ddl-auto: update      
    properties:
      hibernate:
        format_sql: true
  
  #devtool      
  devtools:
    livereload:
      enabled: true
      
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.kpsec.model.dto
     
      